version: '3.8'

services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5435:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql